# Generated by Django 6.1 on 2026-08-30 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_stockmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('stock_forecast', 'Prévision de Stock'), ('cost_optimization', 'Optimisation des Coûts'), ('seasonal_trend', 'Tendance Saisonnière'), ('supplier_performance', 'Performance Fournisseur')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('data_json', models.JSONField(default=dict, help_text='Données additionnelles en JSON')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_products', models.ManyToManyField(blank=True, to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('low_stock', 'Stock Bas'), ('expiring', 'Expiration Proche'), ('expired', 'Expiré'), ('overstock', 'Surstock'), ('trend', 'Tendance')], max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critique'), ('high', 'Haute'), ('medium', 'Moyenne'), ('low', 'Basse')], default='medium', max_length=20)),
                ('current_stock', models.FloatField()),
                ('minimum_stock', models.FloatField()),
                ('daily_consumption', models.FloatField(default=0, help_text='Consommation moyenne par jour')),
                ('estimated_days_remaining', models.IntegerField(blank=True, help_text='Jours avant rupture', null=True)),
                ('days_until_expiration', models.IntegerField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('recommendation', models.TextField()),
                ('recommended_quantity', models.FloatField(blank=True, help_text='Quantité recommandée à acheter', null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='inventory.product')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'unique_together': {('product', 'analysis_type')},
            },
        ),
    ]
