# Generated by Django 6.1 on 2026-08-20 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockmovement'),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('reason', models.CharField(choices=[('broken', 'Produit cassé'), ('expired', 'Produit expiré'), ('handling_error', 'Erreur de manipulation'), ('other', 'Autre')], default='other', max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_losses', to='inventory.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losses', to='laboratory.labsession')),
            ],
        ),
    ]
